# Use an existing docker image as a base
FROM alpine:3.14

# Download and install dependencies
RUN apk add --update nodejs npm

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Install app dependencies
RUN npm install

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME World

# Run the command to start the app
CMD ["node", "app.js"]
